#!/bin/sh

pkg=gmrun
ver=0.9.3

dir=${pkg}-${ver}

mkdir -p ../$dir

cp -rf $PWD/* ../$dir

(
	cd ../$dir
	./autogen.sh
	rm -rf autom4te.cache
	#rm -rf m4
	rm -f make-release
)

cd ..

tar -Jcf ${dir}.tar.xz $dir

### END ###
