#!/bin/sh

pkg=gmrun
ver=$(grep AC_INIT configure.ac  | cut -f 3 -d '[' | cut -f 1 -d ']')

dir=${pkg}-${ver}

mkdir -p ../$dir

cp -rf $PWD/* ../$dir

(
	cd ../$dir
	./autogen.sh
	rm -rf autom4te.cache
	#rm -rf m4
	rm -f make-release
)

cd ..

tar -Jcf ${dir}.tar.xz $dir

### END ###
